import { Component } from '@angular/core';

@Component({
  selector: 'app-tab2',
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss']
})
export class Tab2Page {
  frequencia432 = 'A frequência 432 hz é bastante eficiente para causar um efeito tranquilizante. Em alguns casos, ela pode ter efeito curativo, já que quando ativada, ela aumentar as atividades do hemisfério direito do cérebro, responsável pela nossa imaginação e nossa criatividade. Essa frequência preenche a mente com sensações de paz e bem-estar, sendo o acompanhamento perfeito para a prática de ioga, exercícios suaves ou dormir.'
  frequencia528 = 'A frequência 528Hz é usada para fazer o DNA humano retornar ao seu estado original, o estado perfeito. Também usado para aumentar a energia vital, clareza da mente, expansão da consciência, despertar ou ativar criatividade, estados profundos de sono, dança e celebração. Um estudo de 2018 no Japão revelou que músicas afinadas na frequência de 528 Hz reduziram o estresse nos sistemas endócrino e nervoso autônomos de maneira significativa, mesmo depois de apenas cinco minutos de audição. Em um estudo publicado no Journal of Addiction Research & Therapy, a frequência de 528 Hz reduziu os efeitos tóxicos do etanol, o ingrediente principal encontrado em bebidas alcóolicas e células. E essa frequência também aumentou a vida celular em cerca de 20%, o que é ainda mais impressionante.'
  frequencia369 = 'A música afinada em 396 Hz remove o medo, a preocupação e a ansiedade do subconsciente. Ela também elimina sentimentos de culpa e convicções negativas subconscientes que bloqueiam o caminho da conquista de objetivos pessoais. Ouvir músicas afinadas nesta frequência ajuda muito quando você deseja sentir ânimo e segurança, e deseja empoderar seus objetivos e sonhos.'
  frequencia639 = 'A frequência de 639 Hz ajuda a equilibrar emoções e melhorar o humor. Ela também promove comunicação, amor, compreensão e harmonia a relacionamentos interpessoais. Músicas em 639 Hz são perfeitas quando você precisa de um impulso significativo no amor e positividade, ou esteja lidando com conflitos em relacionamentos.'
  frequencia741 = 'Músicas afinadas em 741 Hz ajudam na resolução de problemas, purificação do corpo e expressão pessoal. Elas também ajudam a despertar a intuição e a promover uma vida simples e pura. Essa frequência é ideal se você está com dificuldades em adotar um estilo de vida saudável, expressar a criatividade ou revelar seus pensamentos.'
  frequencia852 = 'A frequência de 852 Hz ajuda a substituir pensamentos negativos por positivos, sendo ideal quando o nervosismo ou a ansiedade deixam você sem energia. Ela também ajuda a despertar a intuição e a força interior. Você adorará ouvir músicas em 852 Hz se estiver buscando se comunicar com todos e viver em harmonia com o melhor que há dentro de si.'
  ASMR = 'ASMR (Autonomous Sensory Meridian Response), ou em português Resposta Sensorial Meridiana Autônoma. Resposta porque é algo rápido, causado por um estímulo; Sensorial porque é relacionado a sensações; Meridiana funciona em tripla função, sugerindo pico, mas também orgasmo e as vias de energia da medicina tradicional chinesa; Autônoma porque é algo que vem de dentro.'
  afirmacoes = 'As nossas palavras, sejam faladas ou pensadas, manifestam energias diferentes em nós, que podem harmonizar todo um campo energético (aura) ou desequilibrar, inclusive, o campo eletromagnético de uma casa inteira.. As afirmações positivas são palavras ou frases que causam bem-estar para quem escuta. Junto disso, elas podem mudar um padrão vibratório e até uma crença limitante. Palavras e pensamentos positivos podem mudar o padrão energético ao ponto de ajudar alguém a sair de uma depressão, angústias e vícios. Podem auxiliar a novas crenças serem formadas, podem fazer uma pessoa dormir mais tranquilamente e crianças nutrirem crenças mais positivas e prósperas.'
  leidaatracao = 'A Lei da Atração é uma técnica que utiliza a crença de que a mente e o universo estão conectados por meio da força dos pensamentos. Acredita-se que os pensamentos emitem ondas de energias que chamam ou repelem determinadas vibrações. Em outras palavras, a Lei da atração sugere que se você focar no que deseja é possível que o universo te ajude a tornar em realidade.'
  mantras = 'Mantra é um hino do hinduísmo e budismo, que é dito de forma repetida e tem como objetivo relaxar e induzir um estado de meditação em quem canta ou escuta. Um mantra é definido como um instrumento de pensamento. Os budistas atribuem um poder espiritual aos mantras, que são considerados textos sagrados. Os mantras foram escritos há milhares de anos atrás por mestres e gurus da Índia. Existem vários tipos de mantra, que podem influenciar positivamente uma pessoa em diferentes áreas, como relacionamentos, saúde, dinheiro, prosperidade, etc. Um dos mantras mais conhecidos para atrair dinheiro e prosperidade é o Kubera.'
  constructor() {}

}
